import Head from "next/head";
import Navbar from "../Components/Navbar";
import SearchBar from "../Components/SearchBar";
import Layout from "../layouts/Layout";

export default function Home() {
  return (
    <div className={"w-full h-full flex flex-col flex-1"}>
      <Head>
        <title>Elearning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Layout>
        <SearchBar />
      </Layout>
    </div>
  );
}
